[package]
name = "helixlauncher-meta-gen"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = {version = "0.4", features = ["serde"]}
data-encoding = "2"
futures = "0.3"
helixlauncher-meta = {path = "helix-meta"}
indexmap = "1.9"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_with = "2"
sha1 = "0.10"
thiserror = "1"
tokio = {version = "1.21", features = ["macros", "rt-multi-thread"]}

[workspace]
