name: Rust

on:
  # TODO: setup periodic trigger later
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow-dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # TODO: caching
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run --verbose
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'out'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v1
